- src/main/java/dynamicfps/DynamicFPSMod.java
- src/main/java/dynamicfps/mixin/MinecraftClientMixin.java
- src/main/resources/dynamicfps.mixins.json
This PR adds compatibility for `1.15-Snapshot` (`19w38a`-).
This code supports both `1.14.4` and the current snapshot (and hopefully later ones).
I'm sorry if you don't want to support unstable snapshot versions, but I would be happy if you consider accepting this patch :)
> Add compatibility for 1.15-Snapshot (19w38a-)

- src/main/java/dynamicfps/DynamicFPSMod.java
- src/main/java/dynamicfps/mixin/GameRendererMixin.java
- src/main/java/dynamicfps/mixin/SplashScreenMixin.java
- src/main/resources/dynamicfps.mixins.json
Fixes #31.
This PR fixes the resource reloading screen fadeout animation by adding a mixin to access whether the reload is complete (and therefore it's fading out) and not cancelling if that's the case. The check is the same one that vanilla uses to fade out.
The screen can actually be shown often when you play servers with custom resource packs, even more if those are per-world/per-game, since they can get reloaded every few minutes in some cases.
> Fix resource reload screen fadeout animation

- src/main/java/dynamicfps/DynamicFPSMod.java
- src/main/java/dynamicfps/FlawlessFrames.java
Should fix #40.
Implements the FREX Flawless Frames API (grondag/frex#9) in order to allow other mods to request all frames to be processed until requested to go back to normal operation, such as ReplayMod rendering a video.
The implementation is based on the one from CaffeineMC/sodium-fabric#791 (that is very similar to the one from base FREX, other than ignoring the id of the mod requesting the change, since that's only for debugging).
There's basically a Concurrent Set that stores the token of the mods that have requested Flawless Frames to be active (if any). The tokens are created once per mod (in the `Function`) and stored in their `Consumer` lambdas so they are always the same ones and can be properly removed from the set.
Note that I haven't tested this (other than it launches, …
> Implement FREX Frawless Frames API

- jitpack.yml
Dynamic FPS is helpful in dev environments for reducing slowdowns in IDE when tabbed out of your debug client. This change may fix [dynamic FPS on jitpack](https://jitpack.io/com/github/juliand665/Dynamic-FPS/2.2.0/build.log) to allow for easier importing with automatic downloading of toml4j
> Create jitpack.yml for use in dev environments

- src/main/java/dynamicfps/DynamicFPSMod.java
- src/main/java/dynamicfps/mixin/ToastManagerMixin.java
- src/main/resources/dynamicfps.mixins.json
Resolves #72.
I was not sure whether I should add two additional config options for this, so I've opted to simply delay toasts while the mod is actively reducing the frame rate. If this should be changed please let me know!
> Delay toasts while user is inactive

- README.md
- src/main/java/dynamicfps/DynamicFPSMod.java
- src/main/java/dynamicfps/mixin/GameRendererMixin.java
- src/main/java/dynamicfps/mixin/MinecraftClientMixin.java
- src/main/java/dynamicfps/mixin/ScreenMixin.java
- src/main/java/dynamicfps/mixin/SplashOverlayMixin.java
- src/main/java/dynamicfps/util/DynamicFPSScreen.java
- src/main/java/dynamicfps/util/DynamicFPSSplashOverlay.java
- src/main/java/dynamicfps/util/ScreenOptimizationCompat.java
- src/main/resources/dynamicfps.mixins.json
- src/main/resources/fabric.mod.json
Applies two new optimizations while a screen is obscuring the game:
- Limits framerate to 60, same as vanilla main menu etc.
- Stops rendering the world behind the screen, as it's not visible
This implements #68, however as the only way I could think of to detect that a screen is covering the whole window is whether it renders the background image this optimization sadly does not apply to about half of the vanilla options screens since they are rendered differently. An upside however is that the cloth config screen used by many mods such as this one is affected!
I'm opening this as a PR so it can be tested first by some people to see if this breaks any mods (which I doubt, given how simple this is). You can find a built version here: …
> Stop rendering the world while screens are obscuring the whole window

- src/main/java/dynamicfps/DynamicFPSMod.java
apparently windows still regards minimized windows as visible lol
fixes #84
making a PR because we should make sure this doesn't break on other platforms (though i doubt it would): 
[dynamic-fps-2.4.0+min.zip](https://github.com/juliand665/Dynamic-FPS/files/12081426/dynamic-fps-2.4.0%2Bmin.zip)
> explicitly check for minimization

- src/main/java/dynamicfps/mixin/ToastComponentMixin.java
Previously unfocusing the window made toasts simply disappear, now they will disappear as normal but new ones will not be added as the game will think there are already enough toasts. I'm unsure how I missed this originally, this is obviously a lot better .. 🙂
> Simplify toast delaying to fix toasts disappearing on window unfocus

- src/main/java/dynamicfps/mixin/ScreenMixin.java
- src/main/java/dynamicfps/mixin/StatsScreenMixin.java
- src/main/java/dynamicfps/util/DynamicFPSScreen.java
- src/main/resources/dynamicfps.mixins.json
Applies screen optimization once the screen is no longer transparent (the stats packet has been received from the server).
> Apply screen optimization to stats screen

- src/main/java/dynamic_fps/impl/mixin/DebugScreenOverlayMixin.java
- src/main/resources/dynamic_fps.mixins.json
Resolves #76 by adding a new debug line right under the FPS indicator, but maybe it should be elsewhere(?)
I've decided to use a *very obvious color* for this since it will only display while **not focused** to not be intrusive.
We do not replace the FPS display so other mods can change the way it displays (eg. as frame times, which I've seen mentioned).
I've also added the current power state to this line so it's easier to figure out what the mod is doing, or learn how it works.
> Add information about reduced frame rate to debug screen

- src/main/java/dynamic_fps/impl/mixin/MinecraftMixin.java
- src/main/java/dynamic_fps/impl/mixin/WindowMixin.java
- src/main/resources/dynamic_fps.mixins.json
Fixes #105 by making Fabrication pull the frame rate limit from Dynamic FPS instead of bypassing us.
> Fix incompatibility with Fabrication's uncap_menu_fps option

- src/main/java/dynamic_fps/impl/DynamicFPSMod.java
Fixes #107.
Xaero's screen rendering doesn't like (sometimes/most times) being cancelled due to the suspended power state limit, I assume other mods would also not like it so we will rely on the Minecraft FPS limiter instead as it's already locked to 60.
> Special case suspend limit of 60 FPS to fix other mods' rendering

- src/main/java/dynamic_fps/impl/DynamicFPSMod.java
- src/main/java/dynamic_fps/impl/PowerState.java
Fixes #113. Now only applies suspend when on the actual pause screen.
Seems that sadly this experiment wasn't a good experience after all .. 🥲
> Limit suspended state to pause screen

- src/main/resources/assets/dynamic_fps/lang/en_pt.json
Earlier @LostLuma requested I create these strings, and I had a lot of fun coming up with them!
Originally I was going to change the mod's title to "Dynamic Speed Limit" or something along those lines since that's how the game refers to FPS with Pirate Speak enabled, but I decided to keep it as Dynamic FPS since that was shorter and fit better in the keybind menu. ![The keybinds menu with Pirate Speak](https://github.com/juliand665/Dynamic-FPS/assets/47126456/d208be84-18d3-4490-a306-2feca07e64b3)
Finally, if anyone has any feedback or critiques about the strings I came up with, I'm open to change any of them!
> Add Pirate Speak translation strings

- src/main/resources/assets/dynamic_fps/lang/de_at.json
- src/main/resources/assets/dynamic_fps/lang/de_ch.json
- src/main/resources/assets/dynamic_fps/lang/de_de.json
- src/main/resources/assets/dynamic_fps/lang/pt_pt.json
- src/main/resources/assets/dynamic_fps/lang/zh_hk.json
Same purpose as #120. Will also need to be done for dutch if we get such a translation.
I figure that generally having a not super-specific but working translation is better than none, they can be updated afterwards.
> Duplicate language files used for multiple regions

- src/main/java/dynamic_fps/impl/DynamicFPSMod.java
- src/main/java/dynamic_fps/impl/mixin/SoundEngineMixin.java
- src/main/resources/dynamic_fps.mixins.json
Fixes #55. Closes #56.
Tested with Now Playing on 1.20.1, seems to work as expected even during the dragon fight.
> Pause soundmanager instead of stopping all sounds for zero volumes

- src/main/java/dynamic_fps/impl/GraphicsState.java
- src/main/java/dynamic_fps/impl/compat/ClothConfig.java
- src/main/java/dynamic_fps/impl/util/Localization.java
- src/main/resources/assets/dynamic_fps/lang/de_at.json
- src/main/resources/assets/dynamic_fps/lang/de_ch.json
- src/main/resources/assets/dynamic_fps/lang/de_de.json
- src/main/resources/assets/dynamic_fps/lang/en_us.json
Fixes up some config screen stuff I missed previously because I did not realize it's possible :)
- Volume multiplier and graphics options values use proper labels / are now translatable
- Tooltips as warning for minimal graphics state, and to explain what the toast and gc options do
- The frame rate target slider now has an "Unlimited" option on the right instead of the magic -1 value
> Add tooltips and named slider options to config screen

- src/main/java/dynamic_fps/impl/DynamicFPSMod.java
- src/main/java/dynamic_fps/impl/PowerState.java
- src/main/java/dynamic_fps/impl/config/Config.java
- src/main/java/dynamic_fps/impl/config/DynamicFPSConfig.java
Resolves #133. Allows properly using the pause feature to test performance again.
> Remove suspended power state

- src/main/java/dynamic_fps/impl/DynamicFPSMod.java
- src/main/java/dynamic_fps/impl/config/DynamicFPSConfig.java
Saves the config file atomically to prevent corruption, fixing issues such as #138.
Additionally the config is no longer written to disk every launch, but only on first launch and when modified.
> Atomic config saving

- build.gradle
- src/main/java/dynamic_fps/impl/DynamicFPSMod.java
- src/main/java/dynamic_fps/impl/PowerState.java
- src/main/java/dynamic_fps/impl/compat/ClothConfig.java
- src/main/java/dynamic_fps/impl/config/DynamicFPSConfig.java
- src/main/java/dynamic_fps/impl/mixin/MinecraftMixin.java
- src/main/java/dynamic_fps/impl/mixin/WindowMixin.java
- src/main/java/dynamic_fps/impl/util/event/InputObserver.java
- src/main/java/dynamic_fps/impl/util/event/WindowObserver.java
- src/main/resources/assets/dynamic_fps/lang/de_at.json
- src/main/resources/assets/dynamic_fps/lang/de_ch.json
- src/main/resources/assets/dynamic_fps/lang/de_de.json
- src/main/resources/assets/dynamic_fps/lang/en_us.json
- src/main/resources/assets/dynamic_fps/lang/et_ee.json
- src/main/resources/assets/dynamic_fps/lang/fr_ca.json
- src/main/resources/assets/dynamic_fps/lang/fr_fr.json
- src/main/resources/assets/dynamic_fps/lang/it_it.json
- src/main/resources/assets/dynamic_fps/lang/ko_kr.json
- src/main/resources/assets/dynamic_fps/lang/pl_pl.json
- src/main/resources/assets/dynamic_fps/lang/pt_br.json
- src/main/resources/assets/dynamic_fps/lang/pt_pt.json
- src/main/resources/assets/dynamic_fps/lang/ru_ru.json
- src/main/resources/assets/dynamic_fps/lang/sv_se.json
- src/main/resources/assets/dynamic_fps/lang/tr_tr.json
- src/main/resources/assets/dynamic_fps/lang/uk_ua.json
- src/main/resources/assets/dynamic_fps/lang/vi_vn.json
- src/main/resources/assets/dynamic_fps/lang/zh_cn.json
- src/main/resources/assets/dynamic_fps/lang/zh_tw.json
- src/main/resources/dynamic_fps.accesswidener
- src/main/resources/fabric.mod.json
Resolves #92.
Users can choose to activate an optional `Idle` power state when the window is focused but no input has been sent for an amount of 1 to 30 minutes.
Since this incurs a small runtime cost this functionality is only active for users choosing to use it, and it only runs 20 times per second instead of e.g. every frame.
> Add idle detection and mode

- src/main/java/dynamic_fps/impl/DynamicFPSMod.java
- src/main/java/dynamic_fps/impl/util/event/WindowObserver.java
Fixes the idle checks erroneously always being registered, even when unused.
Also only tracks the last keyboard / mouse input time when the idle checker is enabled.
This doesn't really cause any problems but if we can run less code for users not using a feature we might as well.
> Fix idle checks always being registered

- src/main/java/dynamic_fps/impl/DynamicFPSMod.java
- src/main/java/dynamic_fps/impl/compat/ClothConfig.java
- src/main/java/dynamic_fps/impl/config/DynamicFPSConfig.java
- src/main/java/dynamic_fps/impl/config/Serialization.java
- src/main/java/dynamic_fps/impl/mixin/MinecraftMixin.java
- src/main/resources/assets/dynamic_fps/lang/en_us.json
Allows disabling the 60 FPS limit in the menu.
With VSync enabled it'll completely uncap the FPS, otherwise limit it to the user's limit or 250 (to prevent coil whine).
> Add option to disable the menu FPS limit

- platforms/common/src/main/java/dynamic_fps/impl/DynamicFPSMod.java
- platforms/common/src/main/java/dynamic_fps/impl/PowerState.java
- platforms/common/src/main/java/dynamic_fps/impl/compat/GLFW.java
Fix the mouse cursor being released when using the reduce keybind on Minecraft 1.18.2 and earlier.
> Fix the GLFW mouse workaround applying when reducing FPS via keybind

- platforms/common/src/main/java/dynamic_fps/impl/DynamicFPSMod.java
- platforms/common/src/main/java/dynamic_fps/impl/service/ModCompat.java
- platforms/common/src/main/java/dynamic_fps/impl/service/Platform.java
- platforms/common/src/main/java/dynamic_fps/impl/util/ModCompatHelper.java
- platforms/fabric/src/main/java/net/lostluma/dynamic_fps/impl/fabric/service/FabricModCompat.java
- platforms/fabric/src/main/java/net/lostluma/dynamic_fps/impl/fabric/service/FabricPlatform.java
- platforms/fabric/src/main/resources/fabric.mod.json
- platforms/forge/src/main/java/net/lostluma/dynamic_fps/impl/forge/service/ForgeModCompat.java
- platforms/forge/src/main/java/net/lostluma/dynamic_fps/impl/forge/service/ForgePlatform.java
- platforms/neoforge/src/main/java/net/lostluma/dynamic_fps/impl/neoforge/service/NeoForgeModCompat.java
- platforms/neoforge/src/main/java/net/lostluma/dynamic_fps/impl/neoforge/service/NeoForgePlatform.java
- platforms/quilt/src/main/java/net/lostluma/dynamic_fps/impl/quilt/service/QuiltModCompat.java
- platforms/quilt/src/main/java/net/lostluma/dynamic_fps/impl/quilt/service/QuiltPlatform.java
- platforms/quilt/src/main/resources/quilt.mod.json
Resolves #169.
Adds a check for current and older Fastload versions, and disables our screen optimization if this is the case.
> Add workaround for softlock in combination with Fastload

- platforms/common/src/main/java/dynamic_fps/impl/DynamicFPSMod.java
- platforms/common/src/main/java/dynamic_fps/impl/compat/ClothConfig.java
- platforms/common/src/main/java/dynamic_fps/impl/config/DynamicFPSConfig.java
- platforms/common/src/main/java/dynamic_fps/impl/config/Serialization.java
- platforms/common/src/main/java/dynamic_fps/impl/mixin/SoundEngineMixin.java
- platforms/common/src/main/java/dynamic_fps/impl/util/SmoothVolumeHandler.java
- platforms/common/src/main/resources/assets/dynamic_fps/lang/en_us.json
- platforms/fabric/src/main/resources/fabric.mod.json
- platforms/forge/src/main/resources/META-INF/mods.toml
- platforms/neoforge/src/main/resources/META-INF/neoforge.mods.toml
- platforms/quilt/src/main/resources/quilt.mod.json
Add a smooth transition when changing between different volume multipliers.
By default this feature will transition volume from 100% to 0% within 2 seconds, and reverse within 1 second.
The speed for both upward and downward transition can be adjusted in the config to be a bit shorter or longer.
---
This was originally [added to Dynamic FPS Reforged](https://github.com/N4TH4NOT/Dynamic-FPS-Reforged/commit/054a50e74066317234d79d9a7059f4d992e53f0c) by @N4TH4NOT before we had sound category support or a Forge version.
Since their idea still influenced this a lot (otherwise I wouldn't have had this idea in the first place) I've added them to our credits.
> Smooth volume transition

- platforms/common/src/main/java/dynamic_fps/impl/mixin/WindowMixin.java
With default settings, V-sync disabled and mod in FOCUSSED state, the FPS slider is always at 'Infitiny' state.
Also in WindowMixin class, the value will never be -1 because of the mod factoration.
> Fix the infinite fps bug

- README.md
- platforms/neoforge/src/main/java/net/lostluma/dynamic_fps/impl/neoforge/service/NeoForgeModCompat.java
Same feature as already exists on Fabric / Quilt.  
Will also be copied / adjusted for Forge when backporting.
> Allow other mods to disable the overlay optimization on (Neo)Forge

- platforms/common/src/main/java/dynamic_fps/impl/DynamicFPSMod.java
- platforms/common/src/main/java/dynamic_fps/impl/compat/ClothConfig.java
- platforms/common/src/main/java/dynamic_fps/impl/config/Config.java
- platforms/common/src/main/java/dynamic_fps/impl/mixin/DebugScreenOverlayMixin.java
- platforms/common/src/main/resources/assets/dynamic_fps/data/default_config.json
Add option to enable vsync when switching to a different state.
This option is only enabled by default for the on battery state in the default config.
This isn't the most useful (?), but I figured maybe it's cool to have in modpacks since you don't know the user's actual refresh rate if you want to match it for e.g. the hovered state.
> Add vsync option

- platforms/common/src/main/java/dynamic_fps/impl/mixin/SoundEngineMixin.java
> Fix concurrent modification error modifying sound volume

- platforms/common/src/main/java/dynamic_fps/impl/DynamicFPSMod.java
- platforms/common/src/main/java/dynamic_fps/impl/mixin/OptionsMixin.java
- platforms/common/src/main/resources/dynamic_fps-common.mixins.json
Resolves #213 by reverting any modified settings while the `Options.save` method is being ran.
This sadly causes an additional world reload if using the `minimal` graphics state, however since this bug is exceedingly rare and users are already discouraged from using the `minimal` setting it I think this solution is acceptable.
Other ways of fixing the issue I've considered are way more work to write, maintain, and port to other Minecraft versions.
> Fix runtime modified graphics settings potentially being saved

- platforms/common/src/main/java/dynamic_fps/impl/feature/battery/BaseToast.java
- platforms/common/src/main/java/dynamic_fps/impl/feature/battery/BatteryToast.java
- platforms/common/src/main/java/dynamic_fps/impl/feature/battery/BatteryTracker.java
- platforms/common/src/main/java/dynamic_fps/impl/feature/battery/ErrorToast.java
- platforms/common/src/main/resources/assets/dynamic_fps/lang/en_us.json
Adds an error toast to give info on why the battery feature does not work. Shows up if either:
- the library can not be downloaded (disabled in config)
- the library does not support the system (shouldn't happen, but for completeness sake!)
Here's how it looks, with a normal battery toast as a comparison since I was making sure it works:
> Add error toast with hints

- platforms/common/src/main/java/dynamic_fps/impl/Constants.java
- platforms/common/src/main/java/dynamic_fps/impl/DynamicFPSMod.java
- platforms/common/src/main/java/dynamic_fps/impl/mixin/FramerateLimitTrackerMixin.java
> Fix active FPS limits feeling stuttery

- platforms/common/src/main/java/dynamic_fps/impl/compat/ClothConfig.java
- platforms/common/src/main/resources/assets/dynamic_fps/lang/en_us.json
Small UI change that helps avoid scrolling on lower UI scales when trying to find options.
> Collapse options into groups on general options screen

- platforms/common/src/main/java/dynamic_fps/impl/DynamicFPSMod.java
- platforms/common/src/main/java/dynamic_fps/impl/compat/GLFW.java
- platforms/common/src/main/java/dynamic_fps/impl/feature/battery/BatteryTracker.java
- platforms/common/src/main/java/dynamic_fps/impl/util/Threads.java
Moves battery library initialization to a temporary thread.
Also adds `Threads` helper class so thread-related tasks only need to be changed in one place when porting.
> Fix rendering being blocked initially enabling the battery feature

- platforms/common/src/main/java/dynamic_fps/impl/DynamicFPSMod.java
- platforms/common/src/main/java/dynamic_fps/impl/compat/ClothConfig.java
- platforms/common/src/main/java/dynamic_fps/impl/config/DynamicFPSConfig.java
- platforms/common/src/main/java/dynamic_fps/impl/config/option/IgnoreInitialClick.java
- platforms/common/src/main/java/dynamic_fps/impl/feature/state/ClickIgnoreHandler.java
- platforms/common/src/main/java/dynamic_fps/impl/feature/state/WindowObserver.java
- platforms/common/src/main/resources/assets/dynamic_fps/data/default_config.json
- platforms/common/src/main/resources/assets/dynamic_fps/lang/en_us.json
Adds a new option to ignore input done by clicking on the inactive game window.
Useful to prevent accidental interactions with the game using windows other than the game and clicking it by accident.
> Allow ignoring accidental input clicking on the unfocused window

- platforms/common/src/main/java/dynamic_fps/impl/mixin/SoundEngineMixin.java
Resolves #220
Resolves #224
Resolves #250
Instead of iterating over the map of active sounds we now take a copy of the keys, iterate over that, and manually get the values from the map, checking for missing ones. This should make it impossible for a key/value pair being removed from the map in the background to throw a `ConcurrentModificationException`.
> Fix ConcurrentModificationException updating sound volumes
