build.gradle
gradle.properties
src/main/java/dynamicfps/DynamicFPSMod.java
src/main/java/dynamicfps/mixin/GameRendererMixin.java
src/main/java/dynamicfps/mixin/ThreadExecutorMixin.java

Update to 1.15.1 and fix mixin crash

---

build.gradle
gradle.properties
src/main/java/dynamicfps/HudInfoRenderer.java

Updated Loom, Minecraft, Yarn and Fabric API.
Removed Mod Menu as no 20w17a version exists yet.
Removed Developer Mode as it's discontinued and broken.
Changed rendering of the hud text to work with 20w17a.

Update to 20w17a

---

build.gradle
gradle.properties
src/main/java/dynamicfps/DynamicFPSConfig.java
src/main/java/dynamicfps/DynamicFPSMod.java
src/main/java/dynamicfps/DynamicFPSModMenu.java
src/main/resources/assets/dynamicfps/lang/en_us.json
src/main/resources/fabric.mod.json

Adds a configuration screen, along with a config file, to allow setting whether or not to limit framerate when not focused.

Added a configuration screen and configuration file (Fixes #7)

---

src/main/resources/assets/dynamicfps/lang/pl_pl.json

Done through GitHub because I am too lazy to clone. Basically only done because of the convo earlier on quatcord :V

Polish translation

---

src/main/resources/assets/dynamicfps/lang/ru_ru.json

Fixed grammar and logical errors.

Russian translation improvements

---

src/main/resources/assets/dynamicfps/lang/pt_br.json

pt_br.json

---

build.gradle
gradle.properties
src/main/java/dynamicfps/DynamicFPSMod.java
src/main/java/dynamicfps/util/KeyBindingHandler.java
src/main/java/dynamicfps/util/Localization.java

Update to 1.19

---

src/main/java/dynamicfps/ClothConfigScreenFactory.java
src/main/java/dynamicfps/DynamicFPSConfig.java
src/main/java/dynamicfps/DynamicFPSMod.java
src/main/resources/assets/dynamicfps/lang/en_us.json
src/main/resources/assets/dynamicfps/lang/tr_tr.json

Will resolve #54 
For now; turns off Entity Shadows, Smooth Lighting and clouds; Minimizes Particles; Sets Graphics to Fast.
Let me know if you want to add/remove features.

Turn down graphic settings when unfocused & improve Turkish language translation

---

src/main/java/dynamic_fps/impl/util/ModCompatibility.java

I have a new release that does this (see https://github.com/dima-dencep/rrls/pull/46).

Remove for rrls

---

src/main/resources/assets/dynamic_fps/lang/ru_ru.json

Improve ru_ru.json

---

src/main/resources/assets/dynamic_fps/lang/es_ar.json
src/main/resources/assets/dynamic_fps/lang/es_cl.json
src/main/resources/assets/dynamic_fps/lang/es_ec.json
src/main/resources/assets/dynamic_fps/lang/es_es.json
src/main/resources/assets/dynamic_fps/lang/es_mx.json
src/main/resources/assets/dynamic_fps/lang/es_uy.json
src/main/resources/assets/dynamic_fps/lang/es_ve.json

Spanish translation file, kind of amazed it wasn't created already.

Create all Spanish variants translation files.

---

README.md

Thought I'd give this a try. [Rendered view](https://github.com/LostLuma/Dynamic-FPS/tree/new-readme-and-faq).
The idea is to include everything until the Developer Info section on Modrinth / CurseForge, dev info on GitHub only.

Update readme, add FAQ section

---

src/main/java/dynamic_fps/impl/mixin/SoundEngineMixin.java

Fix master volume resetting to 100% when activating focused power state

---

src/main/java/dynamic_fps/impl/mixin/GameRendererMixin.java

Fix pausing on lost focus not working when rendering is disabled

---

src/main/java/dynamic_fps/impl/DynamicFPSMod.java

Fix minecraft field being potentially unset

---

src/main/java/dynamic_fps/impl/mixin/SoundEngineMixin.java

Fixes #153.
I previously wrongly assumed that all sounds played in Minecraft would use one of the other sound categories, and the master volume only exists to control the gain of the audio. As is seen from the linked bug report this is not the case, so the mod has in effect erroneously reduced the volume for these sounds twice instead of once.
For e.g. a master volume of 50% this means sounds playing on the master category were actually played at 25%, with this effect being more and more noticeable at lower master volumes (since the effect is multiplicative).

Fix sounds without more specific categories being quieter

---

src/main/java/dynamic_fps/impl/DynamicFPSMod.java
src/main/java/dynamic_fps/impl/compat/FREX.java
src/main/java/dynamic_fps/impl/util/event/InputObserver.java
src/main/java/dynamic_fps/impl/util/event/WindowObserver.java

Update idle timeout when receiving window events

---

src/main/resources/assets/dynamic_fps/lang/en_pt.json
src/main/resources/assets/dynamic_fps/lang/lol_us.json

Finally, the lolzcat is here! If any strings don't make sense or need to be changed, then that can also be done, just let me know!
This also has one additional experimental change that I'm not 100% sure about, but it changes the title of the mod in mod menu to be a bit more themed with the LOLCat/Pirate translation (Dynamik MPS, and Dynamic Anchor respectively).

Add LOLCAT language, and update Pirate Speak translations

---

platforms/common/src/main/java/dynamic_fps/impl/DynamicFPSMod.java
platforms/common/src/main/java/dynamic_fps/impl/config/Config.java
platforms/common/src/main/java/dynamic_fps/impl/mixin/SoundEngineMixin.java
platforms/common/src/main/java/dynamic_fps/impl/util/duck/DuckSoundEngine.java

- Fix music not always being paused when volume is set to zero
- Fix sounds resuming when the game is paused and the user navigates away from it

Fix sounds / music pausing and resuming at the wrong times

---

platforms/common/src/main/java/dynamic_fps/impl/DynamicFPSMod.java
platforms/common/src/main/java/dynamic_fps/impl/compat/ClothConfig.java
platforms/common/src/main/java/dynamic_fps/impl/config/DynamicFPSConfig.java
platforms/common/src/main/java/dynamic_fps/impl/config/Serialization.java
platforms/common/src/main/java/dynamic_fps/impl/mixin/DebugScreenOverlayMixin.java
platforms/common/src/main/java/dynamic_fps/impl/util/HudInfoRenderer.java
platforms/common/src/main/resources/assets/dynamic_fps/lang/en_us.json

- Add option to disable the mod in the mod config without showing the HUD message
- Add info on why the mod is disabled in the debug overlay to prevent confusing or aid in troubleshooting
- Preview of this in action, having multiple sources disabling the mod: https://files.lostluma.net/oHO6lS.png

Add config toggle to enable and disable the mod, debug info

---

platforms/common/src/main/java/dynamic_fps/impl/config/Config.java
platforms/common/src/main/java/dynamic_fps/impl/config/Serialization.java

Fixes crash on startup when a mod adding new sound categories got removed from an installation.

Fix crash loading configs containing unknown sound categories

---

platforms/common/src/main/resources/assets/dynamic_fps/lang/en_pt.json
platforms/common/src/main/resources/assets/dynamic_fps/lang/en_ud.json
platforms/common/src/main/resources/assets/dynamic_fps/lang/enws.json
platforms/common/src/main/resources/assets/dynamic_fps/lang/lol_us.json

Now with Shakespearean prose and upside down text! These pretty much follow the same formula as before, I hope they're good!

The Joke Langs Never End

---

platforms/common/src/main/java/dynamic_fps/impl/config/DynamicFPSConfig.java
platforms/common/src/main/java/dynamic_fps/impl/config/Serialization.java

Fixes two issues regarding config de/serialization I've seen users run into over the past little while.

Fix config file de/serialization issues

---

platforms/common/src/main/resources/assets/dynamic_fps/lang/ru_ru.json

Hello! In this PR I've updated the russian translation of your mod to make it more up-to-date.
Feel free to correct me or ask me anything about it, I will answer you and commit changes as soon as I can.
I've been working as a mod translator for quite a while now, so if you like my work, you can consider donating! Thank you! (link in bio)

Update ru_ru.json (Russian)

---

platforms/common/src/main/resources/assets/dynamic_fps/lang/de_at.json
platforms/common/src/main/resources/assets/dynamic_fps/lang/de_ch.json
platforms/common/src/main/resources/assets/dynamic_fps/lang/de_de.json
platforms/common/src/main/resources/assets/dynamic_fps/lang/en_us.json

Since it's now missing quite a few strings ... :)

Update German translations

---

platforms/common/src/main/resources/assets/dynamic_fps/lang/fr_ca.json
platforms/common/src/main/resources/assets/dynamic_fps/lang/fr_fr.json

Update and add missing translations base on en_us.json

Update French translations

---

platforms/common/src/main/resources/assets/dynamic_fps/lang/zh_tw.json

Update Traditional Chinese localization

Update Traditional Chinese (zh_tw.json)

---

platforms/common/src/main/resources/assets/dynamic_fps/lang/tr_tr.json

'Battery' can be translated as 'pil' and 'batarya'. I found 'pil' to be more reasonable.
'Download Natives' is translated as 'Download Additional Libraries'.

Updated and improved tr_tr.json

---

platforms/common/src/main/java/dynamic_fps/impl/DynamicFPSMod.java
platforms/common/src/main/java/dynamic_fps/impl/compat/ClothConfig.java
platforms/common/src/main/java/dynamic_fps/impl/config/BatteryTrackerConfig.java
platforms/common/src/main/java/dynamic_fps/impl/config/Serialization.java
platforms/common/src/main/resources/assets/dynamic_fps/data/default_config.json
platforms/common/src/main/resources/assets/dynamic_fps/lang/en_us.json

Customizable low battery notification percentage

---

platforms/common/src/main/resources/assets/dynamic_fps/lang/pt_br.json

Everything was tested and it is working flawlessly, following Crowdin's official rules and formatting!

Update: Brazilian Portuguese translation
